[package]
name = "bigxmldiff"
version = "0.1.0"
authors = ["Seb Ospina <kraige@gmail.com>"]

[dependencies]
rust-crypto = "0.2.36"
getopts = "0.2"
zmq = "0.8"
rand = "0.5.5"
treexml = "0.6"
serde_json = "1.0.32"
node2object = "0.1.2"

